/* Converted to D from ../include/capi/cef_dialog_handler_capi.h by htod */
module cef_dialog_handler_capi;
// Copyright (c) 2014 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//

//C     #ifndef CEF_INCLUDE_CAPI_CEF_DIALOG_HANDLER_CAPI_H_
//C     #define CEF_INCLUDE_CAPI_CEF_DIALOG_HANDLER_CAPI_H_
//C     #pragma once

//C     #include "include/capi/cef_base_capi.h"
import cef_base_capi;
//C     #include "include/capi/cef_browser_capi.h"
import cef_browser_capi;

//C     #ifdef __cplusplus
//C     extern "C" {
//C     #endif


///
// Callback structure for asynchronous continuation of file dialog requests.
///
//C     typedef struct _cef_file_dialog_callback_t {
  ///
  // Base structure.
  ///
//C       cef_base_t base;

  ///
  // Continue the file selection with the specified |file_paths|. This may be a
  // single value or a list of values depending on the dialog mode. An NULL
  // value is treated the same as calling cancel().
  ///
//C       void (CEF_CALLBACK *cont)(struct _cef_file_dialog_callback_t* self,
//C           cef_string_list_t file_paths);

  ///
  // Cancel the file selection.
  ///
//C       void (CEF_CALLBACK *cancel)(struct _cef_file_dialog_callback_t* self);
//C     } cef_file_dialog_callback_t;
struct _cef_file_dialog_callback_t
{
    cef_base_t base;
    void  function(_cef_file_dialog_callback_t *self, cef_string_list_t file_paths)cont;
    void  function(_cef_file_dialog_callback_t *self)cancel;
}
extern (C):
alias _cef_file_dialog_callback_t cef_file_dialog_callback_t;


///
// Implement this structure to handle dialog events. The functions of this
// structure will be called on the browser process UI thread.
///
//C     typedef struct _cef_dialog_handler_t {
  ///
  // Base structure.
  ///
//C       cef_base_t base;

  ///
  // Called to run a file chooser dialog. |mode| represents the type of dialog
  // to display. |title| to the title to be used for the dialog and may be NULL
  // to show the default title ("Open" or "Save" depending on the mode).
  // |default_file_name| is the default file name to select in the dialog.
  // |accept_types| is a list of valid lower-cased MIME types or file extensions
  // specified in an input element and is used to restrict selectable files to
  // such types. To display a custom dialog return true (1) and execute
  // |callback| either inline or at a later time. To display the default dialog
  // return false (0).
  ///
//C       int (CEF_CALLBACK *on_file_dialog)(struct _cef_dialog_handler_t* self,
//C           struct _cef_browser_t* browser, cef_file_dialog_mode_t mode,
//C           const cef_string_t* title, const cef_string_t* default_file_name,
//C           cef_string_list_t accept_types,
//C           struct _cef_file_dialog_callback_t* callback);
//C     } cef_dialog_handler_t;
struct _cef_dialog_handler_t
{
    cef_base_t base;
    int  function(_cef_dialog_handler_t *self, _cef_browser_t *browser, cef_file_dialog_mode_t mode, cef_string_t *title, cef_string_t *default_file_name, cef_string_list_t accept_types, _cef_file_dialog_callback_t *callback)on_file_dialog;
}
alias _cef_dialog_handler_t cef_dialog_handler_t;


//C     #ifdef __cplusplus
//C     }
//C     #endif

//C     #endif  // CEF_INCLUDE_CAPI_CEF_DIALOG_HANDLER_CAPI_H_
