/* Converted to D from ../include/capi/cef_callback_capi.h by htod */
module cef_callback_capi;
// Copyright (c) 2014 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//

//C     #ifndef CEF_INCLUDE_CAPI_CEF_CALLBACK_CAPI_H_
//C     #define CEF_INCLUDE_CAPI_CEF_CALLBACK_CAPI_H_
//C     #pragma once

//C     #include "include/capi/cef_base_capi.h"
import cef_base_capi;

//C     #ifdef __cplusplus
//C     extern "C" {
//C     #endif


///
// Generic callback structure used for asynchronous continuation.
///
//C     typedef struct _cef_callback_t {
  ///
  // Base structure.
  ///
//C       cef_base_t base;

  ///
  // Continue processing.
  ///
//C       void (CEF_CALLBACK *cont)(struct _cef_callback_t* self);

  ///
  // Cancel processing.
  ///
//C       void (CEF_CALLBACK *cancel)(struct _cef_callback_t* self);
//C     } cef_callback_t;
struct _cef_callback_t
{
    cef_base_t base;
    void  function(_cef_callback_t *self)cont;
    void  function(_cef_callback_t *self)cancel;
}
extern (C):
alias _cef_callback_t cef_callback_t;


///
// Generic callback structure used for asynchronous completion.
///
//C     typedef struct _cef_completion_callback_t {
  ///
  // Base structure.
  ///
//C       cef_base_t base;

  ///
  // Method that will be called once the task is complete.
  ///
//C       void (CEF_CALLBACK *on_complete)(struct _cef_completion_callback_t* self);
//C     } cef_completion_callback_t;
struct _cef_completion_callback_t
{
    cef_base_t base;
    void  function(_cef_completion_callback_t *self)on_complete;
}
alias _cef_completion_callback_t cef_completion_callback_t;


//C     #ifdef __cplusplus
//C     }
//C     #endif

//C     #endif  // CEF_INCLUDE_CAPI_CEF_CALLBACK_CAPI_H_
