/* Converted to D from ../include/capi/cef_resource_handler_capi.h by htod */
module cef_resource_handler_capi;
// Copyright (c) 2014 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//

//C     #ifndef CEF_INCLUDE_CAPI_CEF_RESOURCE_HANDLER_CAPI_H_
//C     #define CEF_INCLUDE_CAPI_CEF_RESOURCE_HANDLER_CAPI_H_
//C     #pragma once

//C     #include "include/capi/cef_base_capi.h"
import cef_base_capi;
//C     #include "include/capi/cef_browser_capi.h"
import cef_browser_capi;
//C     #include "include/capi/cef_callback_capi.h"
//C     #include "include/capi/cef_cookie_capi.h"
//C     #include "include/capi/cef_request_capi.h"
//C     #include "include/capi/cef_response_capi.h"
import cef_response_capi;

//C     #ifdef __cplusplus
//C     extern "C" {
//C     #endif


///
// Structure used to implement a custom request handler structure. The functions
// of this structure will always be called on the IO thread.
///
//C     typedef struct _cef_resource_handler_t {
  ///
  // Base structure.
  ///
//C       cef_base_t base;

  ///
  // Begin processing the request. To handle the request return true (1) and
  // call cef_callback_t::cont() once the response header information is
  // available (cef_callback_t::cont() can also be called from inside this
  // function if header information is available immediately). To cancel the
  // request return false (0).
  ///
//C       int (CEF_CALLBACK *process_request)(struct _cef_resource_handler_t* self,
//C           struct _cef_request_t* request, struct _cef_callback_t* callback);

  ///
  // Retrieve response header information. If the response length is not known
  // set |response_length| to -1 and read_response() will be called until it
  // returns false (0). If the response length is known set |response_length| to
  // a positive value and read_response() will be called until it returns false
  // (0) or the specified number of bytes have been read. Use the |response|
  // object to set the mime type, http status code and other optional header
  // values. To redirect the request to a new URL set |redirectUrl| to the new
  // URL.
  ///
//C       void (CEF_CALLBACK *get_response_headers)(
//C           struct _cef_resource_handler_t* self, struct _cef_response_t* response,
//C           int64* response_length, cef_string_t* redirectUrl);

  ///
  // Read response data. If data is available immediately copy up to
  // |bytes_to_read| bytes into |data_out|, set |bytes_read| to the number of
  // bytes copied, and return true (1). To read the data at a later time set
  // |bytes_read| to 0, return true (1) and call cef_callback_t::cont() when the
  // data is available. To indicate response completion return false (0).
  ///
//C       int (CEF_CALLBACK *read_response)(struct _cef_resource_handler_t* self,
//C           void* data_out, int bytes_to_read, int* bytes_read,
//C           struct _cef_callback_t* callback);

  ///
  // Return true (1) if the specified cookie can be sent with the request or
  // false (0) otherwise. If false (0) is returned for any cookie then no
  // cookies will be sent with the request.
  ///
//C       int (CEF_CALLBACK *can_get_cookie)(struct _cef_resource_handler_t* self,
//C           const struct _cef_cookie_t* cookie);

  ///
  // Return true (1) if the specified cookie returned with the response can be
  // set or false (0) otherwise.
  ///
//C       int (CEF_CALLBACK *can_set_cookie)(struct _cef_resource_handler_t* self,
//C           const struct _cef_cookie_t* cookie);

  ///
  // Request processing has been canceled.
  ///
//C       void (CEF_CALLBACK *cancel)(struct _cef_resource_handler_t* self);
//C     } cef_resource_handler_t;
struct _cef_resource_handler_t
{
    cef_base_t base;
    int  function(_cef_resource_handler_t *self, _cef_request_t *request, _cef_callback_t *callback)process_request;
    void  function(_cef_resource_handler_t *self, _cef_response_t *response, int64 *response_length, cef_string_t *redirectUrl)get_response_headers;
    int  function(_cef_resource_handler_t *self, void *data_out, int bytes_to_read, int *bytes_read, _cef_callback_t *callback)read_response;
    int  function(_cef_resource_handler_t *self, _cef_cookie_t *cookie)can_get_cookie;
    int  function(_cef_resource_handler_t *self, _cef_cookie_t *cookie)can_set_cookie;
    void  function(_cef_resource_handler_t *self)cancel;
}
extern (C):
alias _cef_resource_handler_t cef_resource_handler_t;


//C     #ifdef __cplusplus
//C     }
//C     #endif

//C     #endif  // CEF_INCLUDE_CAPI_CEF_RESOURCE_HANDLER_CAPI_H_
